### ISSUE TITLE
swiftとアプリ開発方法を学ぶ

### ISSUE THREAD

**Issue by alotofwe** [pepabo/railstutorial-ios#14]
https://developer.apple.com/library/prerelease/ios/referencelibrary/GettingStarted/DevelopiOSAppsSwift/index.html

を元に学ぼうと思 (ったけどこれPrerelease版なのでは?)

**Comment by alotofwe** [comment]
# Work with View Controllers

[URL](https://developer.apple.com/library/prerelease/ios/referencelibrary/GettingStarted/DevelopiOSAppsSwift/Lesson4.html#//apple_ref/doc/uid/TP40015214-CH6-SW1)

写真を投稿できるようにする

---

### 全ての作業を終えても，タップしてカメラロールが立ち上がらない

今回開発しようとしている写真アップロード方法はボタンで，ボタンを使うとうまく立ち上がったため，これを採用

### 各オブジェクトのサイズ制約が効いていない

それまでの開発者の手元以外にcloneすると各オブジェクトの制約が効いていない

端末のサイズ指定で`w Compact h Any`で開発していたため，cloneした人もそれに合わせなければならなかった

### Empty name testが落ちる

class側に空文字列でnilを返す制約をつけていなかった

**Comment by alotofwe** [comment]
# Create a Table View

[URL](https://developer.apple.com/library/prerelease/ios/referencelibrary/GettingStarted/DevelopiOSAppsSwift/Lesson7.html#//apple_ref/doc/uid/TP40015214-CH8-SW1)

Table Viewを追加する
ゆくゆくはfeedに応用できる

---

### Storyboardが2画面分に増える

コンフリクト防止のため，各画面ごとにstoryboard filesを分割して管理したい

http://okenprog.hatenablog.com/entry/2015/06/10/074800

> 新たにXcode7らStoryboard ReferenceというStoryboardに配置する用の オブジェクトが追加され、そちらにセグウェイをつなぐことで 別のStoryboardのViewControllerに遷移することが出来るようになりました。

以降，Xcodeのバージョンを 6.4 から 7 beta 5 に変更

### TableViewCellの名前が被る

前の章の`Meal`とかぶるので，独断でMealTableViewCell classに変更

↑誤ってOS Xの `Cocoa Class` を選んでたために挙動が違ったのでした。
正しくはiOSの `Cocoa touch Class`

**Comment by ku00** [comment]
# Implement Navigation

[URL](https://developer.apple.com/library/prerelease/ios/referencelibrary/GettingStarted/DevelopiOSAppsSwift/Lesson8.html#//apple_ref/doc/uid/TP40015214-CH16-SW1)

新規作成画面を追加する。追加とキャンセル。
ゆくゆくはPostに応用できるかと。

**Comment by ku00** [comment]
# 完成したぞ!

https://cloud.githubusercontent.com/assets/2803040/9351125/c309fd30-4691-11e5-899b-23af3f0a3a68.png

**Comment by orzup** [comment]
# 気づいたことを書いていくぞ！

ここのディレクトリ構造も修正したほうがわかりやすいと思うけどどうかな？（これからたくさんクラスが増えそうなので…！）
![image](https://cloud.githubusercontent.com/assets/1712281/9353346/976f1bae-46a2-11e5-861e-bd52e576d6ca.png)

**Comment by alotofwe** [comment]
修正した!

**Comment by ku00** [comment]
#16 でxcode7に移行するのでドキュメントどおりにいけそう(auto layoutとかstory boardとかの機能が)

**Comment by alotofwe** [comment]
完成し，現在はFoodTrackerの撲滅に向けて動いているので，終了と判断します :innocent:

**Comment by ku00** [comment]
:ok_woman:
