### ISSUE TITLE
DeployGateでデプロイ

### ISSUE THREAD

**Issue by alotofwe** [pepabo/railstutorial-ios#15]
testflightを使おうと思いきや，iTunes Connectを利用するためにdeveloper programが必要だったため
deploygateを利用してデプロイを行う

**Comment by alotofwe** [comment]
deploygateでも証明書発行のためにdeveloper program登録が必要だったため
どちらでも必要ならtestfligthを選ぶ (私がtestflightを触ったことがあるため)

**Comment by alotofwe** [comment]
testflightのiTunes Connect接続はadmin権限が必要であり，ペパボから借りたアカウントはagentでログインができない
証明書発行はagentでも行えるため，deploygateを使うことにする
(二転三転して申し訳ない...)

**Comment by orzup** [comment]
無事にdeploygateでインストールできました！

**Comment by hfm** [comment]
:confetti_ball:

**Comment by alotofwe** [comment]
あっ，無言closeしてしまいました...
解決したのでcloseのままにしておきます．
