### ISSUE TITLE
Xcode6.4 から Xcode7 beta5 に移行する

### ISSUE THREAD

**Issue by orzup** [pepabo/railstutorial-ios#16]
Storyboardを複数にわけたいのでXcode7 beta5を使います。
Xcode7 beta5から、Swift 2になるので、FoodTrackerのコードなどを修正していく必要があります。

**Comment by orzup** [comment]
iOS 8.4 シミュレータは別途ダウンロードする必要がありました！
![image](https://cloud.githubusercontent.com/assets/1712281/9375007/c6b132b4-4736-11e5-96b9-dacf515be3a1.png)

**Comment by ku00** [comment]
xcode7でシュミレータiPhone6(iOS 8.4)を起動してみると、キーボードで日本語入力ができない...。
iOS9.0にしてみるとできた(けれどデータの挿入ができない)。

**Comment by ku00** [comment]
<img width="664" alt="2015-08-20 12 39 50" src="https://cloud.githubusercontent.com/assets/2803040/9375189/a0f43ee8-4738-11e5-9bab-f0eb77863ca7.png">

こいつを実行したらディレクトリ階層とかファイルがかなり吹っ飛んだ...(´･_･`)

**Comment by orzup** [comment]
Xcode7で有線で実機にいれてみたところ、無事に日本語入力できた！
べーただからiOS9.0以外の英語入力以外は対応してないのかも〜
無線で実機にいれることができるようになったら、あまり気にしなくてよくはなるのかなあ。

**Comment by ku00** [comment]
### Storyboardの分割について

https://developer.apple.com/library/prerelease/ios/recipes/xcode_help-IB_storyboard/Chapters/AddSBReference.html

> Compatibility: Storyboard references required an app targeting at least iOS 9.0, OS X 10.11, or WatchKit 2.0 for watchOS.

とのことです。
ちなみに現状iOS9.0だとアプリは意図した通りに動きません。

**Comment by ku00** [comment]
xcode7を使ううえで、今後の開発では
- iOS9.0でも動くようにコードを修正
- Storyboardの分割を諦める

のどちらかを選択しないといけない。

でも、チュートリアルは対応してるはずなんだけどなあ...

https://developer.apple.com/library/prerelease/ios/referencelibrary/GettingStarted/DevelopiOSAppsSwift/index.html#//apple_ref/doc/uid/TP40015214-CH2-SW1

> The lessons use prerelease Xcode 7.0 and iOS SDK 9.0. Make sure that you use these versions of Xcode and the iOS SDK as you work through this guide.

**Comment by ku00** [comment]
### かなしみ

xcode6.4に戻ってビルドし直そうとするとコンパイルエラーが発生する。
(ちなみに戻したのはTravis CIが7に対応してないため)

```
Swift Compiler Error
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 11
```

**Comment by ku00** [comment]
Product > Clean でクリーンした後に再ビルドしたら解決した。7でビルドしたときのキャッシュが悪さしてたっぽい?
(しゅんしゅんさん、ありがとうございました!)

**Comment by orzup** [comment]
なぜか、Xcode7 で実機に有線でいれると、Xcode6.4でもお金を払わずに実機にいれることができ、た…なぜだ！！？？

**Comment by orzup** [comment]
移行はしないことになったからとじます！
