### ISSUE TITLE
ねはんもiconほしい

### ISSUE THREAD

**Issue by orzup** [pepabo/railstutorial-ios#17]
ほしい…とりあえずテキトーにつくってみた…:eyes:
色は涅槃図からとってきています。
![image](https://cloud.githubusercontent.com/assets/1712281/9376133/e5ef3cfe-4743-11e5-9490-6408102b6dd1.png)

**Comment by orzup** [comment]
夢がかなったのでクローズします〜！

**Comment by alotofwe** [comment]
夢が叶ってうれしい

**Comment by ku00** [comment]
これで涅槃にいけそう
