### ISSUE TITLE
Xcodeプロジェクトのデバイスがuniversalになってる問題

### ISSUE THREAD

**Issue by orzup** [pepabo/railstutorial-ios#26]
@alotofwe @takuminnnn

![image](https://cloud.githubusercontent.com/assets/1712281/9457837/1591de9e-4b22-11e5-9648-0859ae742431.png)

今、iPad用のアイコンを登録してくれという警告が出続けています（つらい）

取りうる手段として以下の3つが考えられるのですが、
1. 気にしない
2. iPad用のアイコンを登録する
3. **universal から iPhone に変更する**

まず、警告を取り除く方向の 2 か 3 がいいんじゃないかな〜
次に、デバイスはiPhoneで固定されているので 3 かな〜
などと思うのですがどうでしょう。

どれがいいか、お尋ねしたいです:bow:

**Comment by ku00** [comment]
:three:

**Comment by alotofwe** [comment]
:3:

**Comment by orzup** [comment]
おっけ〜！あとで変更しておきます。

**Comment by orzup** [comment]
変更したのでこのイシューは閉じます！
