### ISSUE TITLE
swiftのフォーマットを統一する

### ISSUE THREAD

**Issue by alotofwe** [pepabo/railstutorial-ios#48]
空行に空白は入れるか入れないかなどを統一しなければ

https://github.com/pepabo/railstutorial-ios/commit/d45bb252c2d4df354c510d7f269c1f20536e9d83#commitcomment-12988448

のようなコミットが発生することになるので，ツールを用いてフォーマットを統一したい．

挙げて頂いた候補はclang-format．
Objective-Cでは主流(?)みたいですが，swiftではどうなのか等，調査が必要かと思います．

**Comment by orzup** [comment]
とてもよいissueキタ！clang-format 便利そうだ〜！
個人的には空行の空白は全滅派 :innocent:

**Comment by orzup** [comment]
@takuminnnn にきいたところ、空行の空白は全滅でよいそうなので

ひとまず http://qiita.com/tmnb/items/5774b9494c91f8c34e6f の設定をするのはどうでしょうか〜？
チェックいれるだけでいいので簡単かと〜

**Comment by alotofwe** [comment]
そのチェックを入れてみて試しに空白のみの空行を入れてbuildをしてみても，自動的に削除されない :cat: 
いつのタイミングで削除されるんだろう...

**Comment by orzup** [comment]
新規作成時です！
ファイルごとに、空白は消すだのなんだのっていう設定があるのかな〜すでに設定されるとそれが優先されているようだ…。

**Comment by alotofwe** [comment]
各自チェックを付けて，今後作成するファイルは消してもらうということで，閉じてしまっていいかな...
多分，私のXVimの手動強制インデントで挿入されているだけな気がする

**Comment by orzup** [comment]
いまはそれでよいと思う〜！

**Comment by alotofwe** [comment]
:ok_woman: です
