### ISSUE TITLE
アプリ名を決めよう

### ISSUE THREAD

**Issue by alotofwe** [pepabo/railstutorial-ios#49]
URLからアプリに飛ぶ際に，Schemesを決める必要があります (`xxx://`のxxxの部分)

ここが`foodtracker://`だといつまでも食べ物の呪縛から逃れられないので，
かっこいい名前を決めましょう!

**Comment by alotofwe** [comment]
ちなみにkakiko派です．

**Comment by orzup** [comment]
`kakiko` 〜！

**Comment by ku00** [comment]
`kiteco` を意識するなら `kakico` ?
そうでないなら `kakiko` でいいと思いますよ :cat2:

**Comment by orzup** [comment]
`kakico` かっこいいね！！！！ `co`ってなんだろ？

**Comment by alotofwe** [comment]
確かにkが3つ並ぶよりはかっこいいかもしれない... :cat:

**Comment by alotofwe** [comment]
kaki.co (corporation) ?

**Comment by orzup** [comment]
`kakico`

**Comment by alotofwe** [comment]
:+1:

**Comment by ku00** [comment]
:ok_hand:

**Comment by alotofwe** [comment]
`kakico`に決定したので閉じます~
