### ISSUE TITLE
ペルソナを作る

### ISSUE THREAD

**Issue by orzup** [pepabo/railstutorial-ios#5]
#4 をうけて、ペルソナを作ることに。

ともちゃんができた！
![image](https://cloud.githubusercontent.com/assets/1712281/9323734/bdacf686-45be-11e5-83f8-291e55bf2daf.png)

**Comment by horaotoko** [comment]
:eyes:

**Comment by horaotoko** [comment]
ユーザーイメージを固めよう！って思ったのはとっても :ok_woman: です！
ただ、ボードを見る限りもうちょっとこうしたほうがいいな、これどうなってるんだろうな、
というのがあったのでマサカリを投げます！
- このペルソナが達成したい目標は明文化したうえでチームに共有できてますか？
- 目標を達成するまでのシナリオ（ユーザーストーリー）は文章として残っていますか？
- 「あまり」「よく」「〜代」という言葉が使われていますが、具体的にはどの程度かチームで共有できていますか？
- 想像だけでペルソナをつくっていないですか？「よくいそうな人」ではないですか？

ペルソナは仮想のユーザーですが、「架空」のユーザーではありません。
調査した結果浮かび上がった行動パターンや生活パターンなどから定義されるものです。

ふわっとしたユーザー像は、作り手の都合に合わせて変形していまいます。
本来であればユーザーの都合に作り手が合わせなければいけないですよね。

少なくとも具体的に設定できるところや、目標・シナリオに関しては
チーム外の人に説明しても理解してもらえるくらいの内容を明文化して用意しておくと
説得力のあるUX設計ができるのではないでしょうか！

**Comment by orzup** [comment]
ほらおさん、レビューありがとうございます！！

> ふわっとしたユーザー像は、作り手の都合に合わせて変形していまいます。
> 本来であればユーザーの都合に作り手が合わせなければいけないですよね。

今回、ユーザーの調査をまったく行わずに想像でつくってしまっているので、ずいぶん作り手の都合に合わせて変形してしまっていると思います…

本来なら、開発を行う前にきちんとペルソナを定めるべきだとは思うのですが、
研修のStep1「Rails Tutorialに沿って作ったTwitterに似たWebアプリ用のモバイルアプリを作成する」段階ですので、次のStep2「ユーザー体験を作成する」に着手する前にペルソナについてきちんと再考します！
[研修の内容はこちら](http://blog.hifumi.info/2015/08/18/pepabo-mobile-app-training-2015/)
