### ISSUE TITLE
2015-09-04 ユーザテスト手順

### ISSUE THREAD

**Issue by alotofwe** [pepabo/railstutorial-ios#67]
ユーザテストにて，テスターに行って欲しいものを書きます．
前回から更新された機能を試してもらいます．

**Comment by alotofwe** [comment]
前回から追加された機能は，以下のとおりです．
- Sign Up (Account Activationを含む)
  - 不正な値が入力された際は，エラー内容が表示される
  - 適切な値が入力された際は，アクティベーションを促すメッセージが表示されSign Inに戻る
  - 実際にメールが送信される
  - メールに含まれるURLにアクセスをすると，ブラウザを経由した後にアプリのFeed画面が表示された状態になる
- Log In
  - 登録されていない情報であれば落ちる
  - 登録されている情報を入力した時のみログイン成功
- Password Reset
  - emailの形式になっていれば成功マークが出る (実際にメールは送信されない)
- Micropost
  - 投稿をすると，テキストのみが投稿され，Feed画面に戻る
- Feed
  - ログインしているユーザのfeedが表示されている
  - 投稿をすると，Feed画面の一番上の項目に，その内容が追加されている
  - (上の2つとも，一旦画面外にセルを移動させないと適切に表示されない)
- Config
  - All, Followers, Folloing, Profile editが表示される
- All Users
  - 自分を含めた全てのユーザが表示される
  - 各ユーザの写真をタップすると，プロフィール画面に飛ぶ
- Profile
  - ログインしているユーザのプロフィールが表示される
  - ログインしているユーザのMicropostsが表示される
  - (postsは一旦画面外にセルを移動させないと適切に表示されない)
- Following / Followers
  - ログインしているユーザがフォローしているユーザが表示される
  - ログインしているユーザがフォローされているユーザが表示される

**Comment by ku00** [comment]
singしてる :microphone:  し、そこは log inでよさそう

**Comment by alotofwe** [comment]
:microphone: 

修正しました，上記を元に詳しい手順を書いていきます

**Comment by alotofwe** [comment]
# Sign Up
- 空白のフォームでは，Create my accountボタンが押せない
- フォームを全て埋めた状態で，emailの形式が正しくない場合はボタンが押せない
- emailをa@b.cにすると，既に使われているというエラーが表示される
- passwordとconfirmationが一致していない場合はエラーが表示される
- passwordが6文字未満であればエラーが表示される
- フォームの内容が全て正しい時にCreate my accountを押すと，Log In画面に戻り，アクティベーションを求めるポップアップが表示される

# Account Activation
- アクティベーションを求めるポップアップが表示された後，Sign Up時に入力したemailにメールが届いている
- 届いたメールに書いてあるリンクを踏むと，一旦ブラウザが表示され，その後すぐアプリのFeed画面に移る

**Comment by alotofwe** [comment]
# Log In
- 空白のフォームでは，Log inボタンが押せない
- フォームを全て埋めた状態で，emailの形式が正しくない場合はボタンが押せない
- 登録されていない内容 (例えばemailがa@b.c，passwordがabcdef)でLog inボタンを押すと，エラーが表示される
- 登録されているが，まだアクティベーションを行っていない内容 (例えばact@b.c / password) でLog inボタンを押すと，エラーが表示される
- 登録されている内容 (例えばSing Upで作ったユーザ)でLog inボタンを押すと，Feed画面に移る

**Comment by horaotoko** [comment]
:eyes:

**Comment by alotofwe** [comment]
細かく書いていきましたが，「ユーザテストって何で行うべきなんだっけ?」と話し合って調べた結果
大きくめに
- アカウントを作ってください
- micropostの投稿をしてください

等を言って，テスターがどういう動作を行うかを調べるべきだということになったので
上の`前回から追加された機能`を参考にして，口頭で手順を行ってもらおうということになりました．

ということで，以降の更新はしません...!

**Comment by alotofwe** [comment]
終わったのでcloseします
